const tap = require('tap')
const signatures = require('sodium-signatures')
const { create, post, del } = require('../../src/index')
const MemoryStore = require('../../src/stores/memory')

tap.test('soft delete, with a record', async function(t) {
  const keys = signatures.keyPair()
  const messageStore = new MemoryStore()
  const m = create('hi')
  // console.log("created message:", m)
  const posted = await post(m, { messageStore, keys })
  // console.log("posted message", posted)
  t.ok(posted)
  t.equal(posted.meta.signed.length, 1)
  const mExists = await messageStore.exists(m.meta.hash)
  t.true(mExists)
  const deletedMessage = await del(m.meta.hash, { messageStore, keys })
  t.equal(posted.meta.signed.length, 2)
  const deletionSignature = posted.meta.signed.find(s => s.type === 'deletion')
  t.ok(deletionSignature)
  const refetchedMessage = await messageStore.get(m.meta.hash)
  t.ok(refetchedMessage)
  t.same(refetchedMessage.body, null)
  t.equal(refetchedMessage.meta.signed.length, 2)
})
