const tap = require('tap')
const signatures = require('sodium-signatures')
const { decode } = require('../../util/encoding')
const { create, post } = require('../../commands/index')
const MemoryStore = require('../../stores/memory')
const verify = require('../../commands/verify')

tap.test('post a message', async function(t) {
  const messageStore = new MemoryStore()
  const m = create('hi')
  const posted = await post(m, { messageStore, skipValidation: true })
  t.ok(posted)
  const mExists = await messageStore.exists(m.meta.hash)
  t.true(mExists)
})

tap.test('post a message, sign if there are keys provided', async function(t) {
  const keys = signatures.keyPair()
  const messageStore = new MemoryStore()
  const m = create('hi')
  const posted = await post(m, { messageStore, keys, skipValidation: true })
  t.ok(posted)
  t.ok(posted.meta)
  t.same(posted.meta.signed[0].type, 'route')
  t.same(typeof posted.meta.signed[0].publicKey, 'string')
  t.same(keys.publicKey, decode(posted.meta.signed[0].publicKey))
  const verified = await verify(posted, { all: true })
  t.ok(verified, 'signature should be valid')
})
